### ISSUE TITLE
安卓打包后apk，安装闪退

### ISSUE THREAD

**Issue by shaibaoj** [bmfe/eros#110]
安卓打包正式apk包，安装手机闪退，

通过手机连接到电脑，debug调试方式直接安装到手机是正常的。

**Comment by shaibaoj** [comment]
java.lang.NullPointerException: Attempt to invoke interface method 'void com.taobao.weex.devtools.inspector.network.NetworkEventReporter.requestWillBeSent(com.taobao.weex.devtools.inspector.network.NetworkEventReporter$InspectorRequest)' on a null object reference
                                                       at com.benmu.framework.extend.adapter.WeexOkhttp3Interceptor.intercept(WeexOkhttp3Interceptor.java:67)
                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                       at com.benmu.framework.http.okhttp.log.LoggerInterceptor.intercept(LoggerInterceptor.java:46)

**Comment by hanliuxin5** [comment]
应该已经修复了，静待佳音

**Comment by aa453509345** [comment]
We find it really going to happen on some models and have repaired on the feature branch

**Comment by PerseveranceZ** [comment]
@shaibaoj we fix it in newset sdk, run `eros update android`.
