### ISSUE TITLE
升级2018.03.22安卓sdk后，安卓出现闪退

### ISSUE THREAD

**Issue by ChenArno** [bmfe/eros#112]
### Your questions.
-升级该版本sdk后，出现了一个异常，导致闪退

> 
![default](https://user-images.githubusercontent.com/22111171/37808462-765aa5b4-2e85-11e8-8d54-449bf831ee55.png)

-
### Environment. 
- Mobile model: 小米5
- Mobile system: android 7
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by ChenArno** [comment]
全部重新init一个demo，除了app文件夹，全部更换，跑起来了，

**Comment by ChenArno** [comment]
但是我一点调式界面中的interceptor拦截开关，就报这个错

**Comment by hanliuxin5** [comment]
好像是特殊字符导致的异常，你把那个异常的完成信息帖一下，好调错

**Comment by ChenArno** [comment]
我报异常的全贴吗

**Comment by hanliuxin5** [comment]
你标红框的那一大段

**Comment by ChenArno** [comment]
ok我回家搞一下

**Comment by ChenArno** [comment]
> 03-23 10:42:23.022 6548-6548/com.century.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: com.century.app, PID: 6548
                                                               java.lang.RuntimeException: Could not dispatch event: class android.content.Intent to handler [EventHandler public void com.benmu.framework.extend.mediator.MediatorDocker.onEvent(android.content.Intent)]: Unexpected char 0x5929 at 40 in user-agent value: Android SDK built for x86(Android/7.0) (测试/1.0) Weex/0.18.0 1080x1794
                                                                   at com.squareup.otto.Bus.throwRuntimeException(Bus.java:456)
                                                                   at com.squareup.otto.Bus.dispatch(Bus.java:386)
                                                                   at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:367)
                                                                   at com.squareup.otto.Bus.post(Bus.java:336)
                                                                   at com.benmu.framework.manager.impl.dispatcher.MainThreadBus.post(MainThreadBus.java:18)
                                                                   at com.benmu.framework.activity.DebugActivity$1.onCheckedChanged(DebugActivity.java:59)
                                                                   at android.widget.CompoundButton.setChecked(CompoundButton.java:156)
                                                                   at android.widget.CompoundButton.toggle(CompoundButton.java:115)
                                                                   at android.widget.CompoundButton.performClick(CompoundButton.java:120)
                                                                   at android.view.View$PerformClick.run(View.java:22265)
                                                                   at android.os.Handler.handleCallback(Handler.java:751)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
                                                                Caused by: java.lang.IllegalArgumentException: Unexpected char 0x5929 at 40 in user-agent value: Android SDK built for x86(Android/7.0) (测试/1.0) Weex/0.18.0 1080x1794
                                                                   at okhttp3.Headers$Builder.checkNameAndValue(Headers.java:321)
                                                                   at okhttp3.Headers$Builder.add(Headers.java:271)
                                                                   at okhttp3.Request$Builder.addHeader(Request.java:177)
                                                                   at com.benmu.framework.extend.adapter.DefaultWXHttpAdapter.fetchUrl(DefaultWXHttpAdapter.java:273)
                                                                   at com.benmu.framework.extend.adapter.DefaultWXHttpAdapter.sendRequest(DefaultWXHttpAdapter.java:91)
                                                                   at com.taobao.weex.WXSDKInstance.renderByUrlInternal(WXSDKInstance.java:585)
                                                                   at com.taobao.weex.WXSDKInstance.renderByUrl(WXSDKInstance.java:638)
                                                                   at com.benmu.framework.extend.mediator.MediatorDocker.render(MediatorDocker.java:86)
                                                                   at com.benmu.framework.extend.mediator.MediatorDocker.active(MediatorDocker.java:67)
                                                                   at com.benmu.framework.extend.mediator.MediatorDocker.onEvent(MediatorDocker.java:134)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
                                                                   at com.squareup.otto.Bus.dispatch(Bus.java:384)
                                                                   at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:367) 
                                                                   at com.squareup.otto.Bus.post(Bus.java:336) 
                                                                   at com.benmu.framework.manager.impl.dispatcher.MainThreadBus.post(MainThreadBus.java:18) 
                                                                   at com.benmu.framework.activity.DebugActivity$1.onCheckedChanged(DebugActivity.java:59) 
                                                                   at android.widget.CompoundButton.setChecked(CompoundButton.java:156) 
                                                                   at android.widget.CompoundButton.toggle(CompoundButton.java:115) 
                                                                   at android.widget.CompoundButton.performClick(CompoundButton.java:120) 
                                                                   at android.view.View$PerformClick.run(View.java:22265) 
                                                                   at android.os.Handler.handleCallback(Handler.java:751) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                   at android.os.Looper.loop(Looper.java:154) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

**Comment by hanliuxin5** [comment]
找到原因了，今天提交修复方案

已提交pr

**Comment by myliuyx** [comment]
由于 weex 每次请求的时候都会带上  user-agent 的头信息。其中包含。
Android SDK built for x86  -> 安卓系统平台
(Android/7.0)                      ->  安卓版本
 (测试/1.0)                           ->  native.json  中配置的 appName  和版本
 Weex/0.18.0                      ->  weex sdk 版本
1080x1794                         ->  附加信息（分辨率）

而 okhttp对中文进行了过滤，如果不符合条件就抛出异常。  所以这里的 appName 不能是中文的。
也就是 【(测试/1.0) native.json  中配置的 appName  和版本】  需要修改

新增字符转换方法，合并 @hanliuxin5  PR

**Comment by ChenArno** [comment]
厉害，我的神，不过也感谢@Jony的远程帮忙，修改eros.native.js下的appName改为英文就不报异常了。

**Comment by PerseveranceZ** [comment]
we fix it in newset sdk , run `eros update android`. @ChenArno
