### ISSUE TITLE
wxc-tab-bar用非is-tab-view模式在weex debugger下报ActivityNotFoundException错

### ISSUE THREAD

**Issue by zassq** [bmfe/eros#119]
我用的是3.22的更新版本，用weex-ui的`wxc-tab-bar`在非`is-tab-view`模式下跳转页面的时候报错。
weex debugger下看到这个`ActivityNotFoundException`这个错误

#### `wxc-tab-bar`是这样设置的：
```
<wxc-tab-bar :tab-titles="tabTitles" :tab-styles="tabStyles" title-type="iconFont" wrap-bg-color="transparent" :is-tab-view="false"></wxc-tab-bar>
```

#### 其中`tabTitles`是这样的
```
[
    {
        codePoint: "\ue62f",
        title: "Search",
        url: `${weex.config.eros.jsServer}/dist/js/pages/home/index.js`,
    },
    {
        codePoint: "\ue65f",
        title: "Bookings",
        url: `${weex.config.eros.jsServer}/dist/js/pages/bookings/index.js`,
    },
    {
        codePoint: "\ue618",
        title: "Freebies",
        url: `${weex.config.eros.jsServer}/dist/js/pages/freebies/index.js`,
    },
    {
        codePoint: "\ue615",
        title: "Me",
        url: `${weex.config.eros.jsServer}/dist/js/pages/profile/index.js`,
    }
]
```

#### 然后weex debugger下的错误信息：
```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW cat=[com.taobao.android.intent.category.WEEX] dat=http://192.168.3.13:8889/... (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1878)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1545)
	at android.app.Activity.startActivityForResult(Activity.java:4283)
	at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
	at android.app.Activity.startActivityForResult(Activity.java:4230)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
	at android.app.Activity.startActivity(Activity.java:4567)
	at android.app.Activity.startActivity(Activity.java:4535)
	at com.taobao.weex.appfram.navigator.WXNavigatorModule.push(WXNavigatorModule.java:132)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.taobao.weex.bridge.MethodInvoker.invoke(MethodInvoker.java:46)
	at com.taobao.weex.bridge.NativeInvokeHelper$1.run(NativeInvokeHelper.java:49)
	at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:48)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7224)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

求救~~

**Comment by PerseveranceZ** [comment]
@zassq weex-ui 升级到最新试一下呢？已经到 0.6.x 了

**Comment by zassq** [comment]
@PerseveranceZ 之前用的是0.6.0-beta2
现在升级到0.6.0结果也是一样的，我在weex-ui那也issue了，他们让在`wxcTabBarCurrentTabSelected`事件里跳转，我觉得不太合适
之前看那个严选的demo，是用的`<embed>`标签，我现在只好用这个方案。
但是用`<embed>`会丧失很多life cycle的event，有没有好点的方法做tab呢？请赐教一下~谢谢

**Comment by PerseveranceZ** [comment]
@zassq embed 的话，因为在根节点会触发 life cycle, 配合着当前选中页面的事件，通过发布订阅来交互这样会比较好，但会有些复杂，2种方案都可以，你也可以等待 weex-ui 来修复，他们处理 issue 的速度也很快。

**Comment by zassq** [comment]
@PerseveranceZ 发布订阅啊，页面要是复杂点会挺乱的吧，我先试试发布订阅吧。weex-ui不想提了，我已经被他们打发了，直接close了我的issue，也许我的问题对于他们不是bug，属于使用层面的问题吧...

另外eros很多原生界面文字都是直接hard code的中文，例如扫一扫里的提示文字，我不想直接改framework里的文件的话，大概要如何做呢？主要怕影响以后的升级
因为项目是英文项目...不知道将来eros是否会提供多语言方案？

**Comment by PerseveranceZ** [comment]
@zassq 对于 tab 这样经常业务比较强耦的，我还是建议不要用 ui 库来实现，宁愿自己封装一下，其实不用 embed 也可以自己实现，我们有之前的 [demo](https://github.com/bmfe/eros-template/tree/feature-optimize-webpack/src/js/pages/eros-demos/tab4/demo) 来实现可以支持手势滑动的，自己定义 tab bar 样式的，这样就是把事件分发到每个 page 里面即可，你可以尝试一下。

同时谢谢你的提醒，之后我们会在 SDK 内部兼容国际化方案，如果您的团队这方面的经验，也可以帮我们 pr ，先 close 掉这个 issue。
