### ISSUE TITLE
安卓运行异常

### ISSUE THREAD

**Issue by shaibaoj** [bmfe/eros#128]
java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:877)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:856)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:787)
        at com.benmu.framework.utils.ImageUtil.zoomImage(ImageUtil.java:81)
        at com.benmu.framework.extend.adapter.DefaultWXImageAdapter.handleError(DefaultWXImageAdapter.java:245)
        at com.benmu.framework.extend.adapter.DefaultWXImageAdapter.setImage(DefaultWXImageAdapter.java:214)
        at com.taobao.weex.ui.component.WXImage.autoReleaseImage(WXImage.java:283)
        at com.taobao.weex.ui.view.WXImageView.autoReleaseImage(WXImageView.java:242)
        at com.taobao.weex.ui.view.WXImageView.onWindowVisibilityChanged(WXImageView.java:197)
        at android.view.View.dispatchWindowVisibilityChanged(View.java:10573)
        at com.taobao.weex.ui.view.WXImageView.dispatchWindowVisibilityChanged(WXImageView.java:186)
        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1315)
        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1315)
        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1315)
        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1315)
        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1315)

**Comment by shaibaoj** [comment]
![177df41a-0234-462f-aea4-6718078e794f](https://user-images.githubusercontent.com/6300361/38250915-9caaa94c-3715-11e8-9398-decc02a9cb0e.png)

**Comment by hanliuxin5** [comment]
width and height must be > 0

你加的什么代码导致的报错？

**Comment by shaibaoj** [comment]
<template>
    <div class="wrapper">
        <image :style="{ width, height }" @load="resize" :src="src" />
    </div>
</template>
<script>
export default {
    props: {
        src: {type: String,default: ''},
    },
    data () {
      return {
        width: 1,
        height: 1
      }
    },
    methods: {
      resize (event) {
        if (event.success) {
          let ratio = event.size.naturalHeight / event.size.naturalWidth
          if(event.size.naturalHeight>1){
            this.width = Math.min(event.size.naturalWidth, 730)
            this.height = this.width * ratio
            // console.log("-------------------"+this.width+"--"+this.height);
          }
        }
      }
    }
}
</script>
<style scoped>
 .wrapper {
    justify-content: center;
    align-items: center;
  }
</style>

**Comment by shaibaoj** [comment]
jia

![c4efb111-4697-4db6-bf8c-3b79b3e73d93](https://user-images.githubusercontent.com/6300361/38293385-db72cdfc-37ac-11e8-8e02-b5aa9823e4cf.png)

**Comment by hanliuxin5** [comment]
很明显，你的
```
this.width
this.height
```
其中有算出来的值小于等于０了

**Comment by shaibaoj** [comment]
安卓逻辑 应该是没有的，图片看了 都是真实有尺寸的， 页面打开不会异常， 是关闭后会出这个

**Comment by hanliuxin5** [comment]
如果你在删除这段代码的前提下，无论应用打开关闭与否，都不会出现该异常，那么建议你在赋值之前对宽高做一个判断，确保不会传入无效值
