### ISSUE TITLE
小米应用上传被拒，红米3s内存溢出，请帮忙看一下。。。

### ISSUE THREAD

**Issue by poerlang** [bmfe/eros#144]
### Your questions.
红米3s在启动的时候内存溢出导致闪退，提交被拒，请问这个。。。要怎么调参能通过审核

apk下载链接在这里：

http://pic.bs6s.com/bsnews1.3.6.apk

```
04-22 17:20:05.856 6662 6662 E AndroidRuntime: FATAL EXCEPTION: main
04-22 17:20:05.856 6662 6662 E AndroidRuntime: Process: com.topdevil.news, PID: 6662
04-22 17:20:05.856 6662 6662 E AndroidRuntime: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
04-22 17:20:05.856 6662 6662 E AndroidRuntime: at java.lang.Thread.nativeCreate(Native Method)
04-22 17:20:05.856 6662 6662 E AndroidRuntime: at java.lang.Thread.start(Thread.java:1063)
04-22 17:20:05.856 6662 6662 E AndroidRuntime: at com.topdevil.news.activity.SplashActivity.init(SplashActivity.java:46)
04-22 17:20:05.856 6662 6662 E AndroidRuntime: at com.topdevil.news.activity.SplashActivity.onCreate(SplashActivity.java:29)
04-22 17:20:05.856 6662 6662 E AndroidRuntime: at android.app.Activity.performCreate(Activity.java:6357)
04-22 17:20:05.856 6662 6662 E AndroidRuntime: at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
04-22 17:20:05.856 6662 6662 E AndroidRuntime: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2408)
04-22 17:20:05.856 6662 6662 E AndroidRuntime: at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2515)
04-22 17:20:05.856 6662 6662 E AndroidRuntime: at android.app.ActivityThread.access$1000(ActivityThread.java:154)
04-22 17:20:05.856 6662 6662 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1379)
04-22 17:20:05.856 6662 6662 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:102)
04-22 17:20:05.856 6662 6662 E AndroidRuntime: at android.os.Looper.loop(Looper.java:157)
04-22 17:20:05.856 6662 6662 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:5555)
04-22 17:20:05.856 6662 6662 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
04-22 17:20:05.856 6662 6662 E AndroidRuntime: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
04-22 17:20:05.856 6662 6662 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
```

### Environment. 
- Mobile model: 红米3s
- Dev platform: 安卓

[com.topdevil.news_28.zip](https://github.com/bmfe/eros/files/1936672/com.topdevil.news_28.zip)

**Comment by aa453509345** [comment]
你那边能浮现吗

**Comment by poerlang** [comment]
我手头没有这个机型。。。

**Comment by poerlang** [comment]
仔细看了一下log，有可能是我这边函数调用进入死循环导致的，抱歉抱歉，我再检查一下，先 close。
