### ISSUE TITLE
eros.native.js 中 homePage 设置 tabBar 后，扫描 weex debug的二维码程序闪退

### ISSUE THREAD

**Issue by lyloou** [bmfe/eros#196]
### Your questions.
- eros.native.js 中 homePage 设置 tabBar 后，扫描 weex debug 二维码程序闪退

### Environment. 
- Mobile model: Android
- Mobile system: 6.0.1
- Dev platform: windows
- Node: 8.9.3
- Npm: 6.0.0
- eros-widget: ^1.0.2-beta.1
- weex-ui: ^0.6.4-beta2

### What do you think may be caused by the analysis of the problem.
-  NullPointerException
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.addView(android.view.View)' on a null object reference
        at com.benmu.framework.activity.AbstractWeexActivity.createWXInstance(AbstractWeexActivity.java:466)
        at com.benmu.framework.activity.AbstractWeexActivity.renderPage(AbstractWeexActivity.java:414)
        at com.benmu.framework.activity.AbstractWeexActivity$1.onReceive(AbstractWeexActivity.java:153)
        at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
        at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
        at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:179)
        at android.app.ActivityThread.main(ActivityThread.java:5769)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
```

**Comment by myliuyx** [comment]
已修复！ 近期上线
