### ISSUE TITLE
使用less 的 mixins 时报错

### ISSUE THREAD

**Issue by beyai** [bmfe/eros#215]
node: 10.1.0
os: mac osx

### less 代码
```
.btn() {
	color: #fff;
}

.title {
	.btn(); //错误行
}

```

### 错误代码
```
ERROR in /usr/local/lib/node_modules/eros-cli/node_modules/_weex-vue-loader@0.6.9@weex-vue-loader/lib/style-loader.js!/usr/local/lib/node_modules/eros-cli/node_modules/_less-loader@4.1.0@less-loader/dist/cjs.js!/usr/local/lib/node_modules/eros-cli/node_modules/_weex-vue-loader@0.6.9@weex-vue-loader/lib/style-rewriter.js?id=data-v-67e28a9a!/usr/local/lib/node_modules/eros-cli/node_modules/_weex-vue-loader@0.6.9@weex-vue-loader/lib/selector.js?type=styles&index=0!./src/js/pages/hello.vue
Module build failed: CssSyntaxError: /Volumes/workspace/App/mj/src/js/pages/hello.vue:30:2: Unknown word
    at Input.error (/usr/local/lib/node_modules/eros-cli/node_modules/_postcss@6.0.23@postcss/lib/input.js:119:22)
    at Parser.unknownWord (/usr/local/lib/node_modules/eros-cli/node_modules/_postcss@6.0.23@postcss/lib/parser.js:506:26)
    at Parser.other (/usr/local/lib/node_modules/eros-cli/node_modules/_postcss@6.0.23@postcss/lib/parser.js:171:18)
    at Parser.parse (/usr/local/lib/node_modules/eros-cli/node_modules/_postcss@6.0.23@postcss/lib/parser.js:84:26)
    at parse (/usr/local/lib/node_modules/eros-cli/node_modules/_postcss@6.0.23@postcss/lib/parse.js:24:16)
    at new LazyResult (/usr/local/lib/node_modules/eros-cli/node_modules/_postcss@6.0.23@postcss/lib/lazy-result.js:70:24)
    at Processor.process (/usr/local/lib/node_modules/eros-cli/node_modules/_postcss@6.0.23@postcss/lib/processor.js:117:12)
    at Object.module.exports (/usr/local/lib/node_modules/eros-cli/node_modules/_weex-vue-loader@0.6.9@weex-vue-loader/lib/style-rewriter.js:96:6)
 @ ./src/js/pages/hello.vue?entry=true 5:20-471

```

**Comment by beyai** [comment]
应该是weex-vue-loader问题

**Comment by PerseveranceZ** [comment]
@beyai 可以给 weexteam 提 issue.
