### ISSUE TITLE
如何配置sass？

### ISSUE THREAD

**Issue by overarchingSky** [bmfe/eros#239]
### eros模板项目eros dev启动失败
-下面是错误信息
```
ERROR in /usr/local/lib/node_modules/eros-cli/node_modules/.0.6.11@weex-vue-loader/lib/style-loader.js!/usr/local/lib/node_modules/eros-cli/node_modules/.6.0.7@sass-loader/lib/loader.js!/usr/local/lib/node_modules/eros-cli/node_modules/.0.6.11@weex-vue-loader/lib/style-rewriter.js?id=data-v-faca0f04!./node_modules/bui-weex/src/css/searchbar.scss
Module build failed: CssSyntaxError: /Users/tianlong/Documents/study/eros/node_modules/bui-weex/src/css/searchbar.scss:2:1: Unknown word
You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser
    at Input.error (/usr/local/lib/node_modules/eros-cli/node_modules/.6.0.23@postcss/lib/input.js:119:22)
    at Parser.unknownWord (/usr/local/lib/node_modules/eros-cli/node_modules/.6.0.23@postcss/lib/parser.js:506:26)
    at Parser.other (/usr/local/lib/node_modules/eros-cli/node_modules/.6.0.23@postcss/lib/parser.js:171:18)
    at Parser.parse (/usr/local/lib/node_modules/eros-cli/node_modules/.6.0.23@postcss/lib/parser.js:84:26)
    at parse (/usr/local/lib/node_modules/eros-cli/node_modules/.6.0.23@postcss/lib/parse.js:24:16)
    at new LazyResult (/usr/local/lib/node_modules/eros-cli/node_modules/.6.0.23@postcss/lib/lazy-result.js:70:24)
    at Processor.process (/usr/local/lib/node_modules/eros-cli/node_modules/.6.0.23@postcss/lib/processor.js:117:12)
    at Object.module.exports (/usr/local/lib/node_modules/eros-cli/node_modules/.0.6.11@weex-vue-loader/lib/style-rewriter.js:96:6)
...
```
weex-ui中大量使用了sass文件，但模板项目中没有找到webapck的配置文件，尝试手动安装过sass,sass-loader,node-sass，失败告终，目前感觉无从下手。
### Environment. 
- Mobile model:***
- Mobile system: ***
- Dev platform: mac
- Node: 10.4.1
- Npm:6.1.0
- eros-cli:2.0.8-beta.3

**Comment by PerseveranceZ** [comment]
eros 本身就支持 sass 的，直接 npm 下载 weex ui 就能使用了啊

**Comment by overarchingSky** [comment]
@PerseveranceZ 我是通过脚手架init的模板项目，然后cnpm i后eros dev，就出现了上述的错误

**Comment by sgssxf** [comment]
@overarchingSky 尽量避免使用cnpm，会有各种意想不到的问题

**Comment by overarchingSky** [comment]
好像模板更新了，使用新的模板就可以了

**Comment by congpeijun** [comment]
现在还有这个问题好像
