### ISSUE TITLE
关闭页面，报错 ImmutableDomObject.$jacocoData' cannot be written to by method 

### ISSUE THREAD

**Issue by zhongerbing666** [bmfe/eros#380]
### Your questions.
-关闭页面崩溃，目前集成到老项目
-
### Environment. 
- Mobile model: genymotion android 8.0
- Dev platform: windows

2019-03-18 23:52:48.643 4412-4412/com.benmu.wx E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.benmu.wx, PID: 4412
    java.lang.IllegalAccessError: Final field 'com.taobao.weex.dom.ImmutableDomObject.$jacocoData' cannot be written to by method 'boolean[] com.taobao.weex.dom.ImmutableDomObject$$CC.$jacocoInit$$STATIC$$()' (declaration of 'com.taobao.weex.dom.ImmutableDomObject$$CC' appears in /data/app/com.benmu.wx-uSA7itESsgEw14dwUXBV3w==/base.apk)
        at com.taobao.weex.dom.ImmutableDomObject$$CC.$jacocoInit$$STATIC$$(Unknown Source:17)
        at com.taobao.weex.dom.ImmutableDomObject.<clinit>(Unknown Source:0)
        at com.taobao.weex.ui.component.WXComponent.destroy(WXComponent.java:1687)
        at com.taobao.weex.ui.component.WXText.destroy(WXText.java:176)
        at com.taobao.weex.ui.component.WXVContainer.destroy(WXVContainer.java:216)
        at com.taobao.weex.ui.component.WXScroller.destroy(WXScroller.java:347)
        at com.eros.framework.extend.hook.ui.components.HookWxScroller.destroy(HookWxScroller.java:219)
        at com.taobao.weex.ui.component.WXVContainer.destroy(WXVContainer.java:216)
        at com.taobao.weex.WXSDKInstance.destroy(WXSDKInstance.java:1319)
        at com.taobao.weex.WXSDKInstance.onActivityDestroy(WXSDKInstance.java:964)
        at com.eros.framework.activity.AbstractWeexActivity.onDestroy(AbstractWeexActivity.java:566)
        at com.eros.framework.activity.MainActivity.onDestroy(MainActivity.java:147)
        at android.app.Activity.performDestroy(Activity.java:7177)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1248)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4425)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4456)
        at android.app.ActivityThread.-wrap5(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1654)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

- [ ] 

- [ ]

**Comment by PerseveranceZ** [comment]
demo 运行起来有问题吗

**Comment by zhongerbing666** [comment]
> demo 运行起来有问题吗

demo会卡在download这一步，不知道为什么

**Comment by zhongerbing666** [comment]
> demo 运行起来有问题吗

![微信截图_20190319135314](https://user-images.githubusercontent.com/39330832/54583196-642bb000-4a4e-11e9-9b3d-d8ee1da9a9c1.png)

**Comment by PerseveranceZ** [comment]
是使用 git bash 拉的吗 可以翻墙试试 或者中断了多试几次

**Comment by zhongerbing666** [comment]
> 是使用 git bash 拉的吗 可以翻墙试试 或者中断了多试几次

demo运行没问题，不会闪退。

**Comment by PerseveranceZ** [comment]
是老 eros 项目迁移吗？
